# Interactive component

## New Interactive Features:
In order to have a better understanding of overall long-term trend of Average Part Weight among products inspected by Machine I4, our team will use d3.js to add a interactive feature, showing the Date and Average Part Weight Difference Ratio from Target for each point along the line. For d3.js part, we firstly create a tooltip and attach the appropriate Mouseover, Mousemove, and Mouseout event functions to dynamically move and change the visibility of a tooltip and help display the data values as the text. That newly added feature will help the user obtain the exact value of each data point without going back to check the data table anymore, and it could draw user's attention while providing  additional information.

## Instructions for users:
When the user moves the mouse pointer over the point along the line, the Date and Average Part Weight Difference Ratio from Target values will be displayed near the point in a black box. In addition, nothing will show on the graph when the mouse is away from the any point on the line.



<html lang="en">
    <head>
        <meta charset="utf-8">
        <title></title>
        <script src="https://d3js.org/d3.v7.js"></script>
    <style>
      .tooltip {
          position: absolute;
          pointer-events: none;
          background: #000;
          color: #fff;
          padding: 10px;
          border-radius: 10px;
          font-size: 12px;
        }
    </style>
    </head>
    <body>
    <h3>Average Part Weight Difference Ratio from Target of Each Product 
        Inspected by Machine I4</h3>
      
    <svg id="withaxes" width="600" height="400"></svg>
    <script>
      const svg2 = d3.select("svg#withaxes")

      const margin = {top: 20, right: 0, bottom: 40, left: 70}

      const width =  +svg2.attr("width") - margin.left - margin.right

      const height = +svg2.attr("height") - margin.top - margin.bottom

      const g = svg2.append("g").attr("transform", `translate(${margin.left}, ${margin.top})`);
      g.append("text")
    .attr("class", "x label")
    .attr("text-anchor", "end")
    .attr("x", width-260)
    .attr("y", height +35)
    .text("Date");
    
    g.append("text")
    .attr("class", "y label")
    .attr("text-anchor", "end")
    .attr("y", -60)
    .attr("dy", ".95em")
    .attr("x", -50)
    .attr("transform", "rotate(-90)")
    .text("Average Part Weight Difference Ratio");

      const parseTime = d3.timeParse("%y-%m-%d");
      const formatTime = d3.timeFormat("%B %d, %Y")

      xScale = d3.scaleTime().range([0, width]);

      yScale = d3.scaleLinear()
        .domain([-0.17, 0.15])
        .range([height, 0])

      const xAxis = d3.axisBottom()
        .scale(xScale)
        .tickFormat(d3.timeFormat("%b"));


      const line = d3.line()
        .x(d => xScale(d.date))
        .y(d => yScale(d.Part_Weight));
      var tooltip = d3.select("body")
      	      .append("div")
              
              .style("z-index", "10")
              .style("opacity", "0")
              
      	      .attr("class", "tooltip");
      const data =
      [{'date': '22-09-01', 'Part_Weight': -0.0356},
 {'date': '22-09-02', 'Part_Weight': 0.0437},
 {'date': '22-09-03', 'Part_Weight': 0.0834},
 {'date': '22-09-04', 'Part_Weight': 0.0773},
 {'date': '22-09-05', 'Part_Weight': 0.0702},
 {'date': '22-09-06', 'Part_Weight': 0.027},
 {'date': '22-09-07', 'Part_Weight': -0.0079},
 {'date': '22-09-08', 'Part_Weight': -0.0286},
 {'date': '22-09-09', 'Part_Weight': 0.0297},
 {'date': '22-09-10', 'Part_Weight': 0.0559},
 {'date': '22-09-11', 'Part_Weight': -0.0038},
 {'date': '22-09-12', 'Part_Weight': 0.0675},
 {'date': '22-09-13', 'Part_Weight': 0.0498},
 {'date': '22-09-14', 'Part_Weight': -0.0727},
 {'date': '22-09-15', 'Part_Weight': -0.0418},
 {'date': '22-09-16', 'Part_Weight': -0.085},
 {'date': '22-09-17', 'Part_Weight': -0.0595},
 {'date': '22-09-18', 'Part_Weight': -0.0509},
 {'date': '22-09-19', 'Part_Weight': -0.0108},
 {'date': '22-09-20', 'Part_Weight': 0.0491},
 {'date': '22-09-21', 'Part_Weight': 0.0446},
 {'date': '22-09-22', 'Part_Weight': -0.0449},
 {'date': '22-09-23', 'Part_Weight': -0.0794},
 {'date': '22-09-24', 'Part_Weight': 0.0104},
 {'date': '22-09-26', 'Part_Weight': 0.0509},
 {'date': '22-09-27', 'Part_Weight': -0.0333},
 {'date': '22-09-28', 'Part_Weight': 0.0278},
 {'date': '22-09-29', 'Part_Weight': -0.0437},
 {'date': '22-09-30', 'Part_Weight': -0.0795},
 {'date': '22-10-01', 'Part_Weight': -0.0676},
 {'date': '22-10-02', 'Part_Weight': -0.0601},
 {'date': '22-10-03', 'Part_Weight': -0.0546},
 {'date': '22-10-04', 'Part_Weight': 0.1219},
 {'date': '22-10-05', 'Part_Weight': 0.0803},
 {'date': '22-10-06', 'Part_Weight': 0.0883},
 {'date': '22-10-07', 'Part_Weight': 0.125},
 {'date': '22-10-08', 'Part_Weight': 0.0842},
 {'date': '22-10-09', 'Part_Weight': 0.0816},
 {'date': '22-10-10', 'Part_Weight': 0.1065},
 {'date': '22-10-11', 'Part_Weight': 0.0707},
 {'date': '22-10-12', 'Part_Weight': 0.0595},
 {'date': '22-10-13', 'Part_Weight': 0.1385},
 {'date': '22-10-14', 'Part_Weight': 0.1606},
 {'date': '22-10-15', 'Part_Weight': 0.1462},
 {'date': '22-10-16', 'Part_Weight': 0.1333},
 {'date': '22-10-17', 'Part_Weight': 0.1338},
 {'date': '22-10-18', 'Part_Weight': 0.0892},
 {'date': '22-10-19', 'Part_Weight': 0.0812},
 {'date': '22-10-20', 'Part_Weight': 0.08},
 {'date': '22-10-21', 'Part_Weight': 0.0738},
 {'date': '22-10-22', 'Part_Weight': 0.0922},
 {'date': '22-10-23', 'Part_Weight': 0.1076},
 {'date': '22-10-24', 'Part_Weight': 0.0689},
 {'date': '22-10-25', 'Part_Weight': 0.0169},
 {'date': '22-10-26', 'Part_Weight': -0.0904},
 {'date': '22-10-27', 'Part_Weight': 0.0404},
 {'date': '22-10-28', 'Part_Weight': 0.0574},
 {'date': '22-10-29', 'Part_Weight': 0.0443},
 {'date': '22-10-30', 'Part_Weight': 0.0523},
 {'date': '22-11-01', 'Part_Weight': 0.0275},
 {'date': '22-11-02', 'Part_Weight': 0.0375},
 {'date': '22-11-03', 'Part_Weight': 0.0501},
 {'date': '22-11-04', 'Part_Weight': 0.0277},
 {'date': '22-11-05', 'Part_Weight': -0.0423},
 {'date': '22-11-06', 'Part_Weight': 0.0274},
 {'date': '22-11-12', 'Part_Weight': -0.1308},
 {'date': '22-11-13', 'Part_Weight': 0.1005},
 {'date': '22-11-14', 'Part_Weight': 0.1088},
 {'date': '22-11-15', 'Part_Weight': -0.0995},
 {'date': '22-11-16', 'Part_Weight': 0.011},
 {'date': '22-11-17', 'Part_Weight': 0.0394},
 {'date': '22-11-18', 'Part_Weight': 0.0382},
 {'date': '22-11-22', 'Part_Weight': 0.0391},
 {'date': '22-11-23', 'Part_Weight': 0.0621},
 {'date': '22-11-24', 'Part_Weight': -0.0633},
 {'date': '22-11-28', 'Part_Weight': -0.0721},
 {'date': '22-11-29', 'Part_Weight': -0.0348},
 {'date': '22-11-30', 'Part_Weight': 0.0023},
 {'date': '22-12-01', 'Part_Weight': 0.053}
];
      data.forEach(function(d) {
            d.date = parseTime(d.date);
      });
      
      xScale
        .domain(d3.extent(data, d => d.date))

      g.append("g")
          .attr("transform", `translate(0, ${height})`)
          .call(xAxis);

      g.append("g")
          .call(d3.axisLeft(yScale))

      function goyellow() {
        d3.select(this)
          .append(text)
            .attr("x", "100")
            .attr("y", "40")
            .text("date");
            };
      g.append("path")
          .datum(data)
          .attr("class", "line")
          .attr("fill", "none")
          .attr("stroke", "blue")
          .attr("stroke-width", 2)
          .attr("d", line)
          .on("mouseover", mouseoverFunc)
          .on("mousemove", mousemoveFunc)
      		.on("mouseout", mouseoutFunc);
      const [min, max] = d3.extent(data, d=>d.date);
      function mouseoverFunc(mouse, d) {
        //coordinates
        const [x_cord,y_cord] = d3.pointer(mouse);
        
        const current_date = xScale.invert(x_cord);
        const current_Part_Weight = yScale.invert(y_cord);
        return tooltip
            .style("opacity", "1")
            .html("Date: " + formatTime(current_date) + "<br/> Part_Weight: " + current_Part_Weight)
            .style("left", (x_cord+150) + "px")
            .style("top", (y_cord+500) + "px")
		    }

	      function mousemoveFunc(mouse, d) {
		      const [x_cord,y_cord] = d3.pointer(mouse);
          const current_date = xScale.invert(x_cord);
          const current_Part_Weight = yScale.invert(y_cord);
          return tooltip
          .style("opacity", "1")
            .html("Date: " + formatTime(current_date) + "<br/> Part_Weight: " + current_Part_Weight)
            .style("left", (x_cord+450) + "px")
            .style("top", (y_cord+500) + "px")
	      }

	      function mouseoutFunc(d) {
          return tooltip.style("opacity", "0")
        }
          
    </script>
    </body>
</html>